site_name: Recursos Daw
site_url: https://osca958.github.io/recursosDaw 
theme:
  name: material
  palette:
  
    #Paleta para modo claro
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    #Paleta para modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  


